name: Update ChangeLog on Branch Creation

on:
  create:
    branches:
      - release/QA-*

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # To fetch all history for changelog

    - name: Set up Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

    - name: Fetch develop branch
      run: |
        git fetch origin develop:develop

    - name: Get new commits from develop
      run: |
        git log origin/develop -n 10 --oneline > new_commits.txt

    - name: Update ChangeLog.md
      run: |
        echo "## Release $(date +'%Y-%m-%d')" >> CHANGELOG.md
        cat new_commits.txt >> CHANGELOG.md
        echo "" >> CHANGELOG.md

    - name: Commit and push changeLog.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the default GITHUB_TOKEN
      run: |
        git add changeLog.md
        git commit -m "Update changeLog.md for branch ${{ github.ref_name }}"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/k3255/test-sj.git ${{ github.ref_name }}
